FROM python:3.9
WORKDIR /app
COPY . .
RUN pip3 install -r requirements.txt
CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0"]
# nguyendinhhoang-backend            latest           4c6376a3809d   6 hours ago     925MB