db = db.getSiblingDB("flaskdb");
db.student.drop();

db.student.insertMany([
{'STT': '1', 'Tên ứng viên': 'Bùi Minh Sơn', 'Năm sinh': '2002', 'Giới tính': 'Nam', 'Trường': 'Đại học Công nghệ - Đại học Quốc gia Hà Nội', 'Chuyên ngành': 'Công nghệ thông tin'},
{'STT': '2', 'Tên ứng viên': 'Đào Đại Hiệp', 'Năm sinh': '2001', 'Giới tính': 'Nam', 'Trường': 'Đại học Bách khoa Hà Nội', 'Chuyên ngành': 'Điện tử viễn thông'},
{'STT': '3', 'Tên ứng viên': 'Đỗ Anh Tú', 'Năm sinh': '2002', 'Giới tính': 'Nam', 'Trường': 'Đại học Công nghệ - Đại học Quốc gia Hà Nội', 'Chuyên ngành': 'Mạng máy tính và truyền thông dữ liệu'},
{'STT': '4', 'Tên ứng viên': 'Đỗ Bảo Hoàng', 'Năm sinh': '1997', 'Giới tính': 'Nam', 'Trường': 'Đại học CNTT, cơ khí & quang học St.Petersburg LB Nga', 'Chuyên ngành': 'An toàn thông tin'},
{'STT': '5', 'Tên ứng viên': 'Hoàng Quốc Doanh', 'Năm sinh': '2001', 'Giới tính': 'Nam', 'Trường': 'Đại Học Bách Khoa Hà Nội', 'Chuyên ngành': 'None'},
{'STT': '6', 'Tên ứng viên': 'Le Minh Duc', 'Năm sinh': '2002', 'Giới tính': 'Nam', 'Trường': 'Đại Học Bách Khoa Hà Nội', 'Chuyên ngành': 'Công nghệ thông tin ứng dụng phần mềm'},
{'STT': '7', 'Tên ứng viên': 'Lê Phúc Lai', 'Năm sinh': '2002', 'Giới tính': 'Nam', 'Trường': 'Đại Học Bách Khoa Hà Nội', 'Chuyên ngành': 'Kỹ thuật điện tử viễn thông'},
{'STT': '8', 'Tên ứng viên': 'Lê Quang Anh', 'Năm sinh': '1997', 'Giới tính': 'Nam', 'Trường': 'Đại học CNTT, cơ khí & quang học St.Petersburg LB Nga', 'Chuyên ngành': 'An toàn thông tin'},
{'STT': '9', 'Tên ứng viên': 'Lê Trọng Minh', 'Năm sinh': '2000', 'Giới tính': 'Nam', 'Trường': 'Đại học CNTT, cơ khí & quang học St.Petersburg LB Nga', 'Chuyên ngành': 'Kỹ thuật điều khiển và tự động hóa'},
{'STT': '10', 'Tên ứng viên': 'Lê Tùng Lâm', 'Năm sinh': '1999', 'Giới tính': 'Nam', 'Trường': 'Đại Học Bách Khoa Hà Nội', 'Chuyên ngành': 'Khoa học máy tính'},
{'STT': '11', 'Tên ứng viên': 'Lê Văn Chiến', 'Năm sinh': '2002', 'Giới tính': 'Nam', 'Trường': 'Đại học Công nghệ - Đại học Quốc gia Hà Nội', 'Chuyên ngành': 'Kỹ thuật hàng không vũ trụ'},
{'STT': '12', 'Tên ứng viên': 'Linh Thi Nguyen', 'Năm sinh': '2002', 'Giới tính': 'Nữ', 'Trường': 'Đại Học Bách Khoa Hà Nội', 'Chuyên ngành': 'ICT'},
{'STT': '13', 'Tên ứng viên': 'Nguyễn Đại An', 'Năm sinh': '2023', 'Giới tính': 'Nam', 'Trường': 'Đại Học Bách Khoa Hà Nội', 'Chuyên ngành': 'Khoa học máy tính'},
{'STT': '14', 'Tên ứng viên': 'Nguyễn Đình Hoàng', 'Năm sinh': '2002', 'Giới tính': 'Nam', 'Trường': 'Đại học Công nghệ - Đại học Quốc gia Hà Nội', 'Chuyên ngành': 'Công nghệ thông tin ứng dụng phần mềm'},
{'STT': '15', 'Tên ứng viên': 'Nguyen Duc Vinh Data', 'Năm sinh': '2002', 'Giới tính': 'Nam', 'Trường': 'Học viện Công nghệ Bưu chính Viễn thông', 'Chuyên ngành': 'None'},
{'STT': '16', 'Tên ứng viên': 'Nguyễn Dương Long', 'Năm sinh': '2002', 'Giới tính': 'Nam', 'Trường': 'ĐH Thuỷ lợi', 'Chuyên ngành': 'Công nghệ thông tin ứng dụng phần mềm'},
{'STT': '17', 'Tên ứng viên': 'Nguyen Huu Thang', 'Năm sinh': '2000', 'Giới tính': 'Nam', 'Trường': 'Đại Học Bách Khoa Hà Nội', 'Chuyên ngành': 'Khoa học máy tính'},
{'STT': '18', 'Tên ứng viên': 'Nguyễn Mạnh Cường', 'Năm sinh': '1997', 'Giới tính': 'Nam', 'Trường': 'Đại học CNTT, cơ khí & quang học St.Petersburg LB Nga', 'Chuyên ngành': 'Điện tử'},
{'STT': '19', 'Tên ứng viên': 'Nguyễn Mạnh Đức', 'Năm sinh': '2002', 'Giới tính': 'Nam', 'Trường': 'Học viện Kỹ thuật mật mã', 'Chuyên ngành': 'An toàn thông tin'},
{'STT': '20', 'Tên ứng viên': 'Nguyễn Ngọc Chung', 'Năm sinh': '2002', 'Giới tính': 'Nam', 'Trường': 'Học viên Công nghệ Bưu chính Viễn Thông HCM', 'Chuyên ngành': 'None'},
{'STT': '21', 'Tên ứng viên': 'Nguyễn Tuấn Anh', 'Năm sinh': '1997', 'Giới tính': 'Nam', 'Trường': 'Đại học CNTT, cơ khí & quang học St.Petersburg LB Nga', 'Chuyên ngành': 'An toàn thông tin'},
{'STT': '22', 'Tên ứng viên': 'Nguyễn Văn Quang', 'Năm sinh': '1997', 'Giới tính': 'Nam', 'Trường': 'Đại học CNTT, cơ khí & quang học St.Petersburg LB Nga', 'Chuyên ngành': 'An toàn thông tin'},
{'STT': '23', 'Tên ứng viên': 'Ninh Chí Hướng', 'Năm sinh': '2002', 'Giới tính': 'Nam', 'Trường': 'Học viện Công nghệ Bưu chính viễn thông', 'Chuyên ngành': 'An toàn thông tin'},
{'STT': '24', 'Tên ứng viên': 'Ninh Văn Nghĩa', 'Năm sinh': '2001', 'Giới tính': 'Nam', 'Trường': 'Đại Học Bách Khoa Hà Nội', 'Chuyên ngành': 'Khoa học máy tính'},
{'STT': '25', 'Tên ứng viên': 'Phạm Anh Đức', 'Năm sinh': '2001', 'Giới tính': 'Nam', 'Trường': 'Đại học Bách Khoa Hà Nội', 'Chuyên ngành': 'Toán ứng dụng và tin học'},
{'STT': '26', 'Tên ứng viên': 'Phạm Duy Cương', 'Năm sinh': '1997', 'Giới tính': 'Nam', 'Trường': 'Đại học CNTT, cơ khí & quang học St.Petersburg LB Nga', 'Chuyên ngành': 'Công nghệ điện tử'},
{'STT': '27', 'Tên ứng viên': 'Phạm Hồng Thanh', 'Năm sinh': '1998', 'Giới tính': 'Nam', 'Trường': 'Swinburne University', 'Chuyên ngành': 'Phát triển phần mềm'},
{'STT': '28', 'Tên ứng viên': 'Phạm Thị Khánh Linh', 'Năm sinh': '2002', 'Giới tính': 'Nữ', 'Trường': 'Đại học Công nghệ - Đại học Quốc gia Hà Nội', 'Chuyên ngành': 'Mạng máy tính và truyền thông dữ liệu'},
{'STT': '29', 'Tên ứng viên': 'Phạm Văn Tới', 'Năm sinh': '2002', 'Giới tính': 'Nam', 'Trường': 'Học viện Công nghệ Bưu chính viễn thông', 'Chuyên ngành': 'Công nghệ thông tin ứng dụng phần mềm'},
{'STT': '30', 'Tên ứng viên': 'Trần Đức Mạnh', 'Năm sinh': '1998', 'Giới tính': 'Nam', 'Trường': 'Đại học CNTT, cơ khí & quang học St.Petersburg LB Nga', 'Chuyên ngành': 'Bảo mật thông tin'},
{'STT': '31', 'Tên ứng viên': 'Trần Mạnh Dũng', 'Năm sinh': '2001', 'Giới tính': 'Nam', 'Trường': 'Học viện Công nghệ Bưu chính Viễn thông', 'Chuyên ngành': 'Điện tử viễn thông'},
{'STT': '32', 'Tên ứng viên': 'Trần Minh Dương', 'Năm sinh': '2002', 'Giới tính': 'Nam', 'Trường': 'Đại học Công nghệ - Đại học Quốc gia Hà Nội', 'Chuyên ngành': 'Mạng máy tính và truyền thông dữ liệu'},
{'STT': '33', 'Tên ứng viên': 'Trần Xuân Phú', 'Năm sinh': '2001', 'Giới tính': 'Nam', 'Trường': 'Trường Đại học Công nghệ thông tin - ĐHQG Tp.Hồ chí Minh', 'Chuyên ngành': 'Khoa học máy tính'},
{'STT': '34', 'Tên ứng viên': 'Vũ Hoàng Long', 'Năm sinh': '2001', 'Giới tính': 'Nam', 'Trường': 'Đại học Bách Khoa Hà Nội', 'Chuyên ngành': 'Khoa học máy tính'},
{'STT': '35', 'Tên ứng viên': 'Vũ Minh Hiếu', 'Năm sinh': '2000', 'Giới tính': 'Nam', 'Trường': 'Đại học CNTT, cơ khí & quang học St.Petersburg LB Nga', 'Chuyên ngành': 'Kỹ thuật phần mềm'}
]);
