from app.models.intern import Intern

interns_data = [
    {
        "name": "Bùi Minh Sơn",
        "year_of_birth": 2002,
        "sex": "Nam",
        "university": "Đại học Công nghệ - Đại học Quốc gia Hà Nội",
        "major": "Công nghệ thông tin",
    },
    {
        "name": "Đào Đại Hiệp",
        "year_of_birth": 2001,
        "sex": "Nam",
        "university": "Đại học Bách khoa Hà Nội",
        "major": "Điện tử viễn thông",
    },
    {
        "name": "Đỗ Anh Tú",
        "year_of_birth": 2002,
        "sex": "Nam",
        "university": "Đại học Công nghệ - Đại học Quốc gia Hà Nội",
        "major": "Mạng máy tính và truyền thông dữ liệu",
    },
    {
        "name": "Đỗ Bảo Hoàng",
        "year_of_birth": 1997,
        "sex": "Nam",
        "university": "Đại học CNTT, cơ khí & quang học St.Petersburg LB Nga",
        "major": "An toàn thông tin",
    },
    {
        "name": "Hoàng Quốc Doanh",
        "year_of_birth": 2001,
        "sex": "Nam",
        "university": "Đại Học Bách Khoa Hà Nội",
        "major": "NULL",
    },
    {
        "name": "Le Minh Duc",
        "year_of_birth": 2002,
        "sex": "Nam",
        "university": "Đại Học Bách Khoa Hà Nội",
        "major": "Công nghệ thông tin ứng dụng phần mềm",
    },
    {
        "name": "Lê Phúc Lai",
        "year_of_birth": 2002,
        "sex": "Nam",
        "university": "Đại Học Bách Khoa Hà Nội",
        "major": "Kỹ thuật điện tử viễn thông",
    },
    {
        "name": "Lê Quang Anh",
        "year_of_birth": 1997,
        "sex": "Nam",
        "university": "Đại học CNTT, cơ khí & quang học St.Petersburg LB Nga",
        "major": "An toàn thông tin",
    },
    {
        "name": "Lê Trọng Minh",
        "year_of_birth": 2000,
        "sex": "Nam",
        "university": "Đại học CNTT, cơ khí & quang học St.Petersburg LB Nga",
        "major": "Kỹ thuật điều khiển và tự động hóa",
    },
    {
        "name": "Lê Tùng Lâm",
        "year_of_birth": 1999,
        "sex": "Nam",
        "university": "Đại Học Bách Khoa Hà Nội",
        "major": "Khoa học máy tính",
    },
    {
        "name": "Lê Văn Chiến",
        "year_of_birth": 2002,
        "sex": "Nam",
        "university": "Đại học Công nghệ - Đại học Quốc gia Hà Nội",
        "major": "Kỹ thuật hàng không vũ trụ",
    },
    {
        "name": "Linh Thi Nguyen",
        "year_of_birth": 2002,
        "sex": "Nữ",
        "university": "Đại Học Bách Khoa Hà Nội",
        "major": "ICT",
    },
    {
        "name": "Nguyễn Đại An",
        "year_of_birth": 2023,
        "sex": "Nam",
        "university": "Đại Học Bách Khoa Hà Nội",
        "major": "Khoa học máy tính",
    },
    {
        "name": "Nguyễn Đình Hoàng",
        "year_of_birth": 2002,
        "sex": "Nam",
        "university": "Đại học Công nghệ - Đại học Quốc gia Hà Nội",
        "major": "Công nghệ thông tin ứng dụng phần mềm",
    },
    {
        "name": "Nguyen Duc Vinh Data",
        "year_of_birth": 2002,
        "sex": "Nam",
        "university": "Học viện Công nghệ Bưu chính Viễn thông",
        "major": "NULL",
    },
    {
        "name": "Nguyễn Dương Long",
        "year_of_birth": 2002,
        "sex": "Nam",
        "university": "ĐH Thuỷ lợi",
        "major": "Công nghệ thông tin ứng dụng phần mềm",
    },
    {
        "name": "Nguyen Huu Thang",
        "year_of_birth": 2000,
        "sex": "Nam",
        "university": "Đại Học Bách Khoa Hà Nội",
        "major": "Khoa học máy tính",
    },
    {
        "name": "Nguyễn Mạnh Cường",
        "year_of_birth": 1997,
        "sex": "Nam",
        "university": "Đại học CNTT, cơ khí & quang học St.Petersburg LB Nga",
        "major": "Điện tử",
    },
    {
        "name": "Nguyễn Mạnh Đức",
        "year_of_birth": 2002,
        "sex": "Nam",
        "university": "Học viện Kỹ thuật mật mã",
        "major": "An toàn thông tin",
    },
    {
        "name": "Nguyễn Ngọc Chung",
        "year_of_birth": 2002,
        "sex": "Nam",
        "university": "Học viên Công nghệ Bưu chính Viễn Thông HCM",
        "major": "NULL",
    },
    {
        "name": "Nguyễn Tuấn Anh",
        "year_of_birth": 1997,
        "sex": "Nam",
        "university": "Đại học CNTT, cơ khí & quang học St.Petersburg LB Nga",
        "major": "An toàn thông tin",
    },
    {
        "name": "Nguyễn Văn Quang",
        "year_of_birth": 1997,
        "sex": "Nam",
        "university": "Đại học CNTT, cơ khí & quang học St.Petersburg LB Nga",
        "major": "An toàn thông tin",
    },
    {
        "name": "Ninh Chí Hướng",
        "year_of_birth": 2002,
        "sex": "Nam",
        "university": "Học viện Công nghệ Bưu chính viễn thông",
        "major": "An toàn thông tin",
    },
    {
        "name": "Ninh Văn Nghĩa",
        "year_of_birth": 2001,
        "sex": "Nam",
        "university": "Đại Học Bách Khoa Hà Nội",
        "major": "Khoa học máy tính",
    },
    {
        "name": "Phạm Anh Đức",
        "year_of_birth": 2001,
        "sex": "Nam",
        "university": "Đại học Bách Khoa Hà Nội",
        "major": "Toán ứng dụng và tin học",
    },
    {
        "name": "Phạm Duy Cương",
        "year_of_birth": 1997,
        "sex": "Nam",
        "university": "Đại học CNTT, cơ khí & quang học St.Petersburg LB Nga",
        "major": "Công nghệ điện tử",
    },
    {
        "name": "Phạm Hồng Thanh",
        "year_of_birth": 1998,
        "sex": "Nam",
        "university": "Swinburne University",
        "major": "Phát triển phần mềm",
    },
    {
        "name": "Phạm Thị Khánh Linh",
        "year_of_birth": 2002,
        "sex": "Nữ",
        "university": "Đại học Công nghệ - Đại học Quốc gia Hà Nội",
        "major": "Mạng máy tính và truyền thông dữ liệu",
    },
    {
        "name": "Phạm Văn Tới",
        "year_of_birth": 2002,
        "sex": "Nam",
        "university": "Học viện Công nghệ Bưu chính viễn thông",
        "major": "Công nghệ thông tin ứng dụng phần mềm",
    },
    {
        "name": "Trần Đức Mạnh",
        "year_of_birth": 1998,
        "sex": "Nam",
        "university": "Đại học CNTT, cơ khí & quang học St.Petersburg LB Nga",
        "major": "Bảo mật thông tin",
    },
    {
        "name": "Trần Mạnh Dũng",
        "year_of_birth": 2001,
        "sex": "Nam",
        "university": "Học viện Công nghệ Bưu chính Viễn thông",
        "major": "Điện tử viễn thông",
    },
    {
        "name": "Trần Minh Dương",
        "year_of_birth": 2002,
        "sex": "Nam",
        "university": "Đại học Công nghệ - Đại học Quốc gia Hà Nội",
        "major": "Mạng máy tính và truyền thông dữ liệu",
    },
    {
        "name": "Trần Xuân Phú",
        "year_of_birth": 2001,
        "sex": "Nam",
        "university": "university Đại học Công nghệ thông tin - ĐHQG Tp.Hồ chí Minh",
        "major": "Khoa học máy tính",
    },
    {
        "name": "Vũ Hoàng Long",
        "year_of_birth": 2001,
        "sex": "Nam",
        "university": "Đại học Bách Khoa Hà Nội",
        "major": "Khoa học máy tính",
    },
    {
        "name": "Vũ Minh Hiếu",
        "year_of_birth": 2000,
        "sex": "Nam",
        "university": "Đại học CNTT, cơ khí & quang học St.Petersburg LB Nga",
        "major": "Kỹ thuật phần mềm",
    },
]


def init_db():
    try:
        for intern in interns_data:
            intern_to_add = Intern(
                name=intern["name"],
                year_of_birth=intern["year_of_birth"],
                university=intern["university"],
            )
            intern_to_add.save()
        print("Added interns to database")
    except:
        print("Error when adding interns to database")
