export const GET_ATTENDEES = "GET_ATTENDEES";
export const ADD_ATTENDEE = "ADD_ATTENDEE";
export const DELETE_ATTENDEE = "DELETE_ATTENDEE";
export const UPDATE_ATTENDEE = "UPDATE_ATTENDEE";
export const GET_SINGLE_ATTENDEE = "GET_SINGLE_ATTENDEE";
